#FROM jenkins/jenkins:lts

#ENV JENKINS_USER=admin
#ENV JENKINS_PASS=admin123

#ENV JAVA_OPTS=-Djenkins.install.runSetupWizard=false

#COPY plugins.txt /usr/share/jenkins/plugins.txt
#RUN jenkins-plugin-cli -f /usr/share/jenkins/plugins.txt

#USER root
# Add Docker's official GPG key:
#RUN for pkg in docker.io docker-doc docker-compose podman-docker containerd runc; do apt-get remove $pkg; done
# Add Docker's official GPG key:
#RUN apt-get update
#RUN apt-get install -y ca-certificates curl
#RUN install -m 0755 -d /etc/apt/keyrings
#RUN curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
#RUN chmod a+r /etc/apt/keyrings/docker.asc
    
    # Add the repository to Apt sources:
#RUN    echo \
#      "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian \
#      $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
#      tee /etc/apt/sources.list.d/docker.list > /dev/null
#RUN apt update
#RUN apt-cache policy docker-ce
#RUN apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
#RUN apt-get update
#RUN apt-get clean
#RUN gpasswd -a jenkins docker 
#RUN usermod -aG docker jenkins

FROM jenkins/jenkins:lts

ENV JENKINS_USER=admin
ENV JENKINS_PASS=admin123

ENV JAVA_OPTS=-Djenkins.install.runSetupWizard=false

COPY plugins.txt /usr/share/jenkins/plugins.txt
RUN jenkins-plugin-cli -f /usr/share/jenkins/plugins.txt

USER root

# Configure Docker repository and install Docker
RUN apt-get update && apt-get install -y \
    ca-certificates \
    curl \
    gnupg \
    && install -m 0755 -d /etc/apt/keyrings \
    && curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc \
    && chmod a+r /etc/apt/keyrings/docker.asc \
    && echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian \
      $(. /etc/os-release && echo "$VERSION_CODENAME") stable" \
      | tee /etc/apt/sources.list.d/docker.list > /dev/null \
    && apt-get update \
    && apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Add Jenkins to docker group
RUN gpasswd -a jenkins docker && usermod -aG docker jenkins